version: "3"
services:
  nginx:
    image: 'nginx:latest'
    ports:
        - 80:80
    volumes:
        - "./app:/usr/share/nginx/html"
        - "./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
        - mysql
        - php

  php:
    build: './docker/php'
    volumes:
      - "./app:/usr/share/nginx/html"
      #- "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    depends_on:
      - mysql

  mysql:
    image: 'mysql:latest'
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ges
        MYSQL_USER: gesystem
        MYSQL_PASSWORD: gesystem
        TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/init.d:/docker-entrypoint-initdb.d"
      - "./docker/mysql/data:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "3000:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
